// Имена для тренировки. Двести исполнителей — сводный канон: редакционные
// списки «величайших», продажи и то, что реально спрашивают на квизах.
//
// Список нужен ровно затем, чтобы загаданное имя было тем, которое есть шанс
// узнать. На случайном наборе букв тренировать нечего: на ощупь половину имени
// достраивает догадка, а догадке нужно, чтобы имя было знакомым. По той же
// причине список не бесконечный — двести имён успевают примелькаться, и это
// не мешает: разбирать надо не имя, а знаки.
//
// Порядок ни на что не влияет, имя берётся случайно. Что из каждого уходит
// в мотор полной азбукой и упрощённой, посчитано в TOP200.md.
export const ARTISTS = [
  "The Beatles",
  "The Rolling Stones",
  "Elvis Presley",
  "Bob Dylan",
  "Michael Jackson",
  "Jimi Hendrix",
  "Led Zeppelin",
  "Pink Floyd",
  "Queen",
  "David Bowie",
  "Prince",
  "Chuck Berry",
  "Aretha Franklin",
  "Stevie Wonder",
  "Ray Charles",
  "James Brown",
  "Little Richard",
  "The Beach Boys",
  "The Who",
  "Bob Marley",
  "Nirvana",
  "Madonna",
  "Johnny Cash",
  "Marvin Gaye",
  "Frank Sinatra",
  "Bruce Springsteen",
  "The Velvet Underground",
  "The Doors",
  "Fleetwood Mac",
  "Eagles",
  "AC/DC",
  "Black Sabbath",
  "Deep Purple",
  "Metallica",
  "U2",
  "Radiohead",
  "The Clash",
  "Ramones",
  "Sex Pistols",
  "Joy Division",
  "The Smiths",
  "R.E.M.",
  "Talking Heads",
  "The Police",
  "Eric Clapton",
  "Cream",
  "The Kinks",
  "Buddy Holly",
  "Roy Orbison",
  "B.B. King",
  "Muddy Waters",
  "Robert Johnson",
  "Louis Armstrong",
  "Duke Ellington",
  "Miles Davis",
  "John Coltrane",
  "Ella Fitzgerald",
  "Billie Holiday",
  "Nina Simone",
  "Sam Cooke",
  "Otis Redding",
  "Etta James",
  "Smokey Robinson",
  "The Temptations",
  "The Supremes",
  "Diana Ross",
  "The Isley Brothers",
  "Sly and the Family Stone",
  "Curtis Mayfield",
  "Al Green",
  "Earth, Wind & Fire",
  "The Jackson 5",
  "Donna Summer",
  "Bee Gees",
  "ABBA",
  "Simon & Garfunkel",
  "Paul Simon",
  "Neil Young",
  "Joni Mitchell",
  "Leonard Cohen",
  "Carole King",
  "Van Morrison",
  "Elton John",
  "Billy Joel",
  "Rod Stewart",
  "Tina Turner",
  "Cher",
  "Dolly Parton",
  "Willie Nelson",
  "Hank Williams",
  "Garth Brooks",
  "Shania Twain",
  "Creedence Clearwater Revival",
  "The Byrds",
  "The Band",
  "Grateful Dead",
  "Janis Joplin",
  "Crosby, Stills & Nash",
  "The Allman Brothers Band",
  "Lynyrd Skynyrd",
  "ZZ Top",
  "Santana",
  "Chicago",
  "Dire Straits",
  "Aerosmith",
  "Kiss",
  "Van Halen",
  "Bon Jovi",
  "Def Leppard",
  "Guns N' Roses",
  "Motörhead",
  "Iron Maiden",
  "Judas Priest",
  "Slayer",
  "Megadeth",
  "Pantera",
  "Alice Cooper",
  "Ozzy Osbourne",
  "Rush",
  "Yes",
  "Genesis",
  "King Crimson",
  "Peter Gabriel",
  "Kate Bush",
  "Frank Zappa",
  "Iggy Pop",
  "Lou Reed",
  "Blondie",
  "New Order",
  "Depeche Mode",
  "The Cure",
  "George Michael",
  "Kraftwerk",
  "Daft Punk",
  "The Prodigy",
  "The Chemical Brothers",
  "Massive Attack",
  "Portishead",
  "Björk",
  "Gorillaz",
  "Pixies",
  "Pearl Jam",
  "Soundgarden",
  "Alice in Chains",
  "Red Hot Chili Peppers",
  "Rage Against the Machine",
  "Nine Inch Nails",
  "Green Day",
  "The Offspring",
  "Blink-182",
  "Weezer",
  "Foo Fighters",
  "Oasis",
  "Blur",
  "Muse",
  "Coldplay",
  "Arctic Monkeys",
  "The White Stripes",
  "The Strokes",
  "Arcade Fire",
  "Linkin Park",
  "System of a Down",
  "Slipknot",
  "Tool",
  "Rammstein",
  "Public Enemy",
  "Run-DMC",
  "N.W.A",
  "Beastie Boys",
  "Wu-Tang Clan",
  "Tupac Shakur",
  "The Notorious B.I.G.",
  "Jay-Z",
  "Nas",
  "Dr. Dre",
  "Snoop Dogg",
  "OutKast",
  "Eminem",
  "Missy Elliott",
  "Lauryn Hill",
  "Kanye West",
  "Kendrick Lamar",
  "Drake",
  "Whitney Houston",
  "Mariah Carey",
  "Janet Jackson",
  "Christina Aguilera",
  "Britney Spears",
  "Beyoncé",
  "Alicia Keys",
  "Usher",
  "Justin Timberlake",
  "Amy Winehouse",
  "Rihanna",
  "Lady Gaga",
  "Taylor Swift",
  "Adele",
  "Bruno Mars",
  "The Weeknd",
  "Ed Sheeran",
];
