// Имена для тренировки. Двести пятьдесят исполнителей: две сотни мирового
// канона — редакционные списки «величайших», продажи и то, что реально
// спрашивают на квизах, — и полсотни русскоязычных, которых ни в один мировой
// список не берут, а на местном квизе спрашивают наравне с остальными.
//
// Список нужен ровно затем, чтобы загаданное имя было тем, которое есть шанс
// узнать. На случайном наборе букв тренировать нечего: на ощупь половину имени
// достраивает догадка, а догадке нужно, чтобы имя было знакомым. По той же
// причине список не бесконечный — две с половиной сотни имён успевают
// примелькаться, и это не мешает: разбирать надо не имя, а знаки.
//
// Порядок ни на что не влияет, имя берётся случайно. Что из каждого уходит
// в мотор полной азбукой и упрощённой, посчитано в TOP200.md и RU50.md.
export const ARTISTS = [
  "The Beatles",
  "The Rolling Stones",
  "Elvis Presley",
  "Bob Dylan",
  "Michael Jackson",
  "Jimi Hendrix",
  "Led Zeppelin",
  "Pink Floyd",
  "Queen",
  "David Bowie",
  "Prince",
  "Chuck Berry",
  "Aretha Franklin",
  "Stevie Wonder",
  "Ray Charles",
  "James Brown",
  "Little Richard",
  "The Beach Boys",
  "The Who",
  "Bob Marley",
  "Nirvana",
  "Madonna",
  "Johnny Cash",
  "Marvin Gaye",
  "Frank Sinatra",
  "Bruce Springsteen",
  "The Velvet Underground",
  "The Doors",
  "Fleetwood Mac",
  "Eagles",
  "AC/DC",
  "Black Sabbath",
  "Deep Purple",
  "Metallica",
  "U2",
  "Radiohead",
  "The Clash",
  "Ramones",
  "Sex Pistols",
  "Joy Division",
  "The Smiths",
  "R.E.M.",
  "Talking Heads",
  "The Police",
  "Eric Clapton",
  "Cream",
  "The Kinks",
  "Buddy Holly",
  "Roy Orbison",
  "B.B. King",
  "Muddy Waters",
  "Robert Johnson",
  "Louis Armstrong",
  "Duke Ellington",
  "Miles Davis",
  "John Coltrane",
  "Ella Fitzgerald",
  "Billie Holiday",
  "Nina Simone",
  "Sam Cooke",
  "Otis Redding",
  "Etta James",
  "Smokey Robinson",
  "The Temptations",
  "The Supremes",
  "Diana Ross",
  "The Isley Brothers",
  "Sly and the Family Stone",
  "Curtis Mayfield",
  "Al Green",
  "Earth, Wind & Fire",
  "The Jackson 5",
  "Donna Summer",
  "Bee Gees",
  "ABBA",
  "Simon & Garfunkel",
  "Paul Simon",
  "Neil Young",
  "Joni Mitchell",
  "Leonard Cohen",
  "Carole King",
  "Van Morrison",
  "Elton John",
  "Billy Joel",
  "Rod Stewart",
  "Tina Turner",
  "Cher",
  "Dolly Parton",
  "Willie Nelson",
  "Hank Williams",
  "Garth Brooks",
  "Shania Twain",
  "Creedence Clearwater Revival",
  "The Byrds",
  "The Band",
  "Grateful Dead",
  "Janis Joplin",
  "Crosby, Stills & Nash",
  "The Allman Brothers Band",
  "Lynyrd Skynyrd",
  "ZZ Top",
  "Santana",
  "Chicago",
  "Dire Straits",
  "Aerosmith",
  "Kiss",
  "Van Halen",
  "Bon Jovi",
  "Def Leppard",
  "Guns N' Roses",
  "Motörhead",
  "Iron Maiden",
  "Judas Priest",
  "Slayer",
  "Megadeth",
  "Pantera",
  "Alice Cooper",
  "Ozzy Osbourne",
  "Rush",
  "Yes",
  "Genesis",
  "King Crimson",
  "Peter Gabriel",
  "Kate Bush",
  "Frank Zappa",
  "Iggy Pop",
  "Lou Reed",
  "Blondie",
  "New Order",
  "Depeche Mode",
  "The Cure",
  "George Michael",
  "Kraftwerk",
  "Daft Punk",
  "The Prodigy",
  "The Chemical Brothers",
  "Massive Attack",
  "Portishead",
  "Björk",
  "Gorillaz",
  "Pixies",
  "Pearl Jam",
  "Soundgarden",
  "Alice in Chains",
  "Red Hot Chili Peppers",
  "Rage Against the Machine",
  "Nine Inch Nails",
  "Green Day",
  "The Offspring",
  "Blink-182",
  "Weezer",
  "Foo Fighters",
  "Oasis",
  "Blur",
  "Muse",
  "Coldplay",
  "Arctic Monkeys",
  "The White Stripes",
  "The Strokes",
  "Arcade Fire",
  "Linkin Park",
  "System of a Down",
  "Slipknot",
  "Tool",
  "Rammstein",
  "Public Enemy",
  "Run-DMC",
  "N.W.A",
  "Beastie Boys",
  "Wu-Tang Clan",
  "Tupac Shakur",
  "The Notorious B.I.G.",
  "Jay-Z",
  "Nas",
  "Dr. Dre",
  "Snoop Dogg",
  "OutKast",
  "Eminem",
  "Missy Elliott",
  "Lauryn Hill",
  "Kanye West",
  "Kendrick Lamar",
  "Drake",
  "Whitney Houston",
  "Mariah Carey",
  "Janet Jackson",
  "Christina Aguilera",
  "Britney Spears",
  "Beyoncé",
  "Alicia Keys",
  "Usher",
  "Justin Timberlake",
  "Amy Winehouse",
  "Rihanna",
  "Lady Gaga",
  "Taylor Swift",
  "Adele",
  "Bruno Mars",
  "The Weeknd",
  "Ed Sheeran",
  // Дальше русскоязычные. Кириллица уходит в мотор транслитерацией, и стоит
  // она места в пятёрке: Ж это ZH, Ч это CH, Щ это SHCH — одна буква имени
  // занимает два слота из пяти, а то и все четыре. «Чиж» заполняет пятёрку
  // целиком, CHIZH; «Лев Лещенко» до фамилии не доходит вовсе, LEVLE.
  //
  // Упрощённая азбука на этой полусотне работает в одну сторону: она трогает
  // 24 имени и все 24 делает короче — длиннее не становится ни одно. Пар EE,
  // EA, TH и PH, из-за которых в латинице освободившееся место достаётся
  // следующей букве и та бывает дороже снятой, здесь не нашлось ни одной,
  // а безусловных замен приходит вдвое больше, чем в латинском блоке: 53
  // буквы на полсотни имён против ста на две сотни. Й, Ы, Я, Ю и Ё приносят
  // Y, В приносит V, З и Ж — Z; «Ария» после них ARIA, «Юрий Антонов» —
  // IURIA, «Чиж» — SHISH.
  "Кино",
  "ДДТ",
  "Аквариум",
  "Машина времени",
  "Наутилус Помпилиус",
  "Алиса",
  "Ария",
  "Чайф",
  "Сплин",
  "Мумий Тролль",
  "Земфира",
  "Агата Кристи",
  "Гражданская оборона",
  "Король и Шут",
  "Пикник",
  "Крематорий",
  "Браво",
  "Секрет",
  "Воскресение",
  "Ленинград",
  "Би-2",
  "Чиж & Co",
  "Ночные снайперы",
  "Звери",
  "Сектор Газа",
  "Владимир Высоцкий",
  "Булат Окуджава",
  "Алла Пугачёва",
  "Муслим Магомаев",
  "София Ротару",
  "Валерий Леонтьев",
  "Лев Лещенко",
  "Юрий Антонов",
  "Песняры",
  "Земляне",
  "Ласковый май",
  "Мираж",
  "Комбинация",
  "Руки Вверх!",
  "Иванушки International",
  "t.A.T.u.",
  "Дискотека Авария",
  "Валерий Меладзе",
  "Дима Билан",
  "МакSим",
  "Полина Гагарина",
  "Баста",
  "Каста",
  "Оксимирон",
  "Скриптонит",
];
